CI

diff --git a/.github/workflows/build-wheels.yml b/.github/workflows/build-wheels.yml
--- a/.github/workflows/build-wheels.yml
+++ b/.github/workflows/build-wheels.yml
@@ -3,7 +3,8 @@ name: build - check - upload
 on:
   push:
     branches:
-    - '*'
+    - 'main'
+    - 'hb.bladebit-ci-update'
     tags:
     - '**'
   pull_request:
@@ -107,225 +108,225 @@ jobs:
     - name: Clean workspace
       uses: Chia-Network/actions/clean-workspace@main
 
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+  #   - name: Checkout code
+  #     uses: actions/checkout@v3
+  #     with:
+  #       fetch-depth: 0
 
-    - uses: Chia-Network/actions/setup-python@main
-      with:
-        python-version: ${{ matrix.python.major-dot-minor }}
+  #   - uses: Chia-Network/actions/setup-python@main
+  #     with:
+  #       python-version: ${{ matrix.python.major-dot-minor }}
 
-    - name: Install pipx
-      run: |
-        pip install pipx
+  #   - name: Install pipx
+  #     run: |
+  #       pip install pipx
 
-    - name: Fetch Bladebit Harvesrter
-      run: |
-        set -exo pipefail
-        curl https://github.com/harold-b/bladebit-test/releases/download/v3-alpha4-fixes/green_reaper-v3.0.0-alpha3-linux-x86-64.tar.gz > green_reaper.tar.gz
-        mkdir -p green_reaper && pushd green_reaper
-        tar -xzvf ../green_reaper.tar.gz
-        sudo mkdir -p /usr/local/include
-        sudo cp -r include /usr/local/include/bladebit
-        sudo cp lib/lib/libbladebit_harvester.so /usr/lib64/libbladebit_harvester.so
-        popd
-        ls -la
-        mkdir -p dist
-        ls -la
-        cp green_reaper/lib/libbladebit_harvester.so dist/
+  #   - name: Fetch Bladebit Harvesrter
+  #     run: |
+  #       set -exo pipefail
+  #       curl https://github.com/harold-b/bladebit-test/releases/download/v3-alpha4-fixes/green_reaper-v3.0.0-alpha3-linux-x86-64.tar.gz > green_reaper.tar.gz
+  #       mkdir -p green_reaper && pushd green_reaper
+  #       tar -xzvf ../green_reaper.tar.gz
+  #       sudo mkdir -p /usr/local/include
+  #       sudo cp -r include /usr/local/include/bladebit
+  #       sudo cp lib/lib/libbladebit_harvester.so /usr/lib64/libbladebit_harvester.so
+  #       popd
+  #       ls -la
+  #       mkdir -p dist
+  #       ls -la
+  #       cp green_reaper/lib/libbladebit_harvester.so dist/
 
 
-    - name: Build and test
-      env:
-        CIBW_PRERELEASE_PYTHONS: True
-        CIBW_BUILD_VERBOSITY_MACOS: 0
-        CIBW_BUILD_VERBOSITY_LINUX: 0
-        CIBW_BUILD_VERBOSITY_WINDOWS: 0
-        CIBW_BUILD: ${{ matrix.python.cibw-build }}
-        CIBW_SKIP: '*-manylinux_i686 *-win32 *-musllinux_*'
-        CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.python.manylinux['arm'] }}
-        CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.python.manylinux['intel'] }}
-        CIBW_ENVIRONMENT_LINUX: "PATH=/project/cmake-3.17.3-Linux-`uname -m`/bin:$PATH"
-        CIBW_BEFORE_ALL_LINUX: >
-          curl -L https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-`uname -m`.sh > cmake.sh
-          && yes | sh cmake.sh | cat
-          && rm -f /usr/bin/cmake
-          && which cmake
-          && cmake --version
-          && uname -a
-        CIBW_BEFORE_BUILD_LINUX: >
-          python -m pip install --upgrade pip
-        CIBW_ARCHS_MACOS: ${{ matrix.os.cibw-archs-macos[matrix.arch.matrix] }}
-        CIBW_BEFORE_ALL_MACOS: >
-          brew install gmp boost cmake
-        CIBW_BEFORE_BUILD_MACOS: >
-          python -m pip install --upgrade pip
-        CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=10.14"
-        CIBW_TEST_REQUIRES: pytest
-        CIBW_TEST_COMMAND: py.test -v {project}/tests
-      run:
-        pipx run --spec='cibuildwheel==2.9.0' cibuildwheel --output-dir dist 2>&1
+  #   - name: Build and test
+  #     env:
+  #       CIBW_PRERELEASE_PYTHONS: True
+  #       CIBW_BUILD_VERBOSITY_MACOS: 0
+  #       CIBW_BUILD_VERBOSITY_LINUX: 0
+  #       CIBW_BUILD_VERBOSITY_WINDOWS: 0
+  #       CIBW_BUILD: ${{ matrix.python.cibw-build }}
+  #       CIBW_SKIP: '*-manylinux_i686 *-win32 *-musllinux_*'
+  #       CIBW_MANYLINUX_AARCH64_IMAGE: ${{ matrix.python.manylinux['arm'] }}
+  #       CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.python.manylinux['intel'] }}
+  #       CIBW_ENVIRONMENT_LINUX: "PATH=/project/cmake-3.17.3-Linux-`uname -m`/bin:$PATH"
+  #       CIBW_BEFORE_ALL_LINUX: >
+  #         curl -L https://github.com/Kitware/CMake/releases/download/v3.17.3/cmake-3.17.3-Linux-`uname -m`.sh > cmake.sh
+  #         && yes | sh cmake.sh | cat
+  #         && rm -f /usr/bin/cmake
+  #         && which cmake
+  #         && cmake --version
+  #         && uname -a
+  #       CIBW_BEFORE_BUILD_LINUX: >
+  #         python -m pip install --upgrade pip
+  #       CIBW_ARCHS_MACOS: ${{ matrix.os.cibw-archs-macos[matrix.arch.matrix] }}
+  #       CIBW_BEFORE_ALL_MACOS: >
+  #         brew install gmp boost cmake
+  #       CIBW_BEFORE_BUILD_MACOS: >
+  #         python -m pip install --upgrade pip
+  #       CIBW_ENVIRONMENT_MACOS: "MACOSX_DEPLOYMENT_TARGET=10.14"
+  #       CIBW_TEST_REQUIRES: pytest
+  #       CIBW_TEST_COMMAND: py.test -v {project}/tests
+  #     run:
+  #       pipx run --spec='cibuildwheel==2.9.0' cibuildwheel --output-dir dist 2>&1
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: packages
-        path: ./dist
+  #   - name: Upload artifacts
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: packages
+  #       path: ./dist
 
-  build-sdist:
-    name: sdist - ${{ matrix.os.name }} ${{ matrix.python.major-dot-minor }} ${{ matrix.arch.name }}
-    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - name: Ubuntu
-            matrix: ubuntu
-            runs-on:
-              arm: [Linux, ARM64]
-              intel: [ubuntu-latest]
-        python:
-          - major-dot-minor: '3.9'
-            matrix: '3.9'
-        arch:
-          - name: Intel
-            matrix: intel
+  # build-sdist:
+  #   name: sdist - ${{ matrix.os.name }} ${{ matrix.python.major-dot-minor }} ${{ matrix.arch.name }}
+  #   runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #         - name: Ubuntu
+  #           matrix: ubuntu
+  #           runs-on:
+  #             arm: [Linux, ARM64]
+  #             intel: [ubuntu-latest]
+  #       python:
+  #         - major-dot-minor: '3.9'
+  #           matrix: '3.9'
+  #       arch:
+  #         - name: Intel
+  #           matrix: intel
 
-    steps:
-    - name: Clean workspace
-      uses: Chia-Network/actions/clean-workspace@main
+  #   steps:
+  #   - name: Clean workspace
+  #     uses: Chia-Network/actions/clean-workspace@main
 
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+  #   - name: Checkout code
+  #     uses: actions/checkout@v3
+  #     with:
+  #       fetch-depth: 0
 
-    - uses: Chia-Network/actions/setup-python@main
-      with:
-        python-version: ${{ matrix.python.major-dot-minor }}
+  #   - uses: Chia-Network/actions/setup-python@main
+  #     with:
+  #       python-version: ${{ matrix.python.major-dot-minor }}
 
-    - name: Build source distribution
-      run: |
-        pip install build
-        python -m build --sdist --outdir dist .
+  #   - name: Build source distribution
+  #     run: |
+  #       pip install build
+  #       python -m build --sdist --outdir dist .
 
-    - name: Upload artifacts
-      uses: actions/upload-artifact@v3
-      with:
-        name: packages
-        path: ./dist
+  #   - name: Upload artifacts
+  #     uses: actions/upload-artifact@v3
+  #     with:
+  #       name: packages
+  #       path: ./dist
 
-  check:
-    name: Check - ${{ matrix.os.name }} ${{ matrix.python.major-dot-minor }} ${{ matrix.arch.name }}
-    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - name: Ubuntu
-            matrix: ubuntu
-            runs-on:
-              arm: [Linux, ARM64]
-              intel: [ubuntu-latest]
-        python:
-          - major-dot-minor: '3.9'
-            matrix: '3.9'
-        arch:
-          - name: Intel
-            matrix: intel
+  # check:
+  #   name: Check - ${{ matrix.os.name }} ${{ matrix.python.major-dot-minor }} ${{ matrix.arch.name }}
+  #   runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #         - name: Ubuntu
+  #           matrix: ubuntu
+  #           runs-on:
+  #             arm: [Linux, ARM64]
+  #             intel: [ubuntu-latest]
+  #       python:
+  #         - major-dot-minor: '3.9'
+  #           matrix: '3.9'
+  #       arch:
+  #         - name: Intel
+  #           matrix: intel
 
-    steps:
-    - name: Clean workspace
-      uses: Chia-Network/actions/clean-workspace@main
+  #   steps:
+  #   - name: Clean workspace
+  #     uses: Chia-Network/actions/clean-workspace@main
 
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+  #   - name: Checkout code
+  #     uses: actions/checkout@v3
+  #     with:
+  #       fetch-depth: 0
 
-    - uses: Chia-Network/actions/setup-python@main
-      with:
-        python-version: ${{ matrix.python.major-dot-minor }}
+  #   - uses: Chia-Network/actions/setup-python@main
+  #     with:
+  #       python-version: ${{ matrix.python.major-dot-minor }}
 
-    - name: flake8
-      run: |
-        pip install flake8
-        flake8 tests setup.py
+  #   - name: flake8
+  #     run: |
+  #       pip install flake8
+  #       flake8 tests setup.py
 
-    - name: mypy
-      run: |
-        pip install mypy
-        mypy --config-file mypi.ini setup.py tests
+  #   - name: mypy
+  #     run: |
+  #       pip install mypy
+  #       mypy --config-file mypi.ini setup.py tests
 
-  upload:
-    name: Upload to PyPI - ${{ matrix.os.name }} ${{ matrix.python.major-dot-minor }} ${{ matrix.arch.name }}
-    runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
-    needs:
-      - build-wheels
-      - build-sdist
-      - check
-    strategy:
-      fail-fast: false
-      matrix:
-        os:
-          - name: Ubuntu
-            matrix: ubuntu
-            runs-on:
-              arm: [Linux, ARM64]
-              intel: [ubuntu-latest]
-        python:
-          - major-dot-minor: '3.9'
-            matrix: '3.9'
-        arch:
-          - name: Intel
-            matrix: intel
+  # upload:
+  #   name: Upload to PyPI - ${{ matrix.os.name }} ${{ matrix.python.major-dot-minor }} ${{ matrix.arch.name }}
+  #   runs-on: ${{ matrix.os.runs-on[matrix.arch.matrix] }}
+  #   needs:
+  #     - build-wheels
+  #     - build-sdist
+  #     - check
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os:
+  #         - name: Ubuntu
+  #           matrix: ubuntu
+  #           runs-on:
+  #             arm: [Linux, ARM64]
+  #             intel: [ubuntu-latest]
+  #       python:
+  #         - major-dot-minor: '3.9'
+  #           matrix: '3.9'
+  #       arch:
+  #         - name: Intel
+  #           matrix: intel
 
-    steps:
-    - name: Clean workspace
-      uses: Chia-Network/actions/clean-workspace@main
+  #   steps:
+  #   - name: Clean workspace
+  #     uses: Chia-Network/actions/clean-workspace@main
 
-    - name: Checkout code
-      uses: actions/checkout@v3
-      with:
-        fetch-depth: 0
+  #   - name: Checkout code
+  #     uses: actions/checkout@v3
+  #     with:
+  #       fetch-depth: 0
 
-    - uses: Chia-Network/actions/setup-python@main
-      with:
-        python-version: ${{ matrix.python.major-dot-minor }}
+  #   - uses: Chia-Network/actions/setup-python@main
+  #     with:
+  #       python-version: ${{ matrix.python.major-dot-minor }}
 
-    - name: Download artifacts
-      uses: actions/download-artifact@v3
-      with:
-        name: packages
-        path: ./dist
+  #   - name: Download artifacts
+  #     uses: actions/download-artifact@v3
+  #     with:
+  #       name: packages
+  #       path: ./dist
 
-    - name: Test for secrets access
-      id: check_secrets
-      shell: bash
-      run: |
-        unset HAS_SECRET
-        if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
-        echo "HAS_SECRET=${HAS_SECRET}" >>$GITHUB_OUTPUT
-      env:
-        SECRET: "${{ secrets.test_pypi_password }}"
+  #   - name: Test for secrets access
+  #     id: check_secrets
+  #     shell: bash
+  #     run: |
+  #       unset HAS_SECRET
+  #       if [ -n "$SECRET" ]; then HAS_SECRET='true' ; fi
+  #       echo "HAS_SECRET=${HAS_SECRET}" >>$GITHUB_OUTPUT
+  #     env:
+  #       SECRET: "${{ secrets.test_pypi_password }}"
 
-    - name: Install twine
-      run: pip install twine
+  #   - name: Install twine
+  #     run: pip install twine
 
-    - name: Publish distribution to PyPI
-      if: startsWith(github.event.ref, 'refs/tags') && steps.check_secrets.outputs.HAS_SECRET
-      env:
-        TWINE_USERNAME: __token__
-        TWINE_NON_INTERACTIVE: 1
-        TWINE_PASSWORD: ${{ secrets.pypi_password }}
-      run: twine upload --non-interactive --skip-existing --verbose 'dist/*'
+  #   - name: Publish distribution to PyPI
+  #     if: startsWith(github.event.ref, 'refs/tags') && steps.check_secrets.outputs.HAS_SECRET
+  #     env:
+  #       TWINE_USERNAME: __token__
+  #       TWINE_NON_INTERACTIVE: 1
+  #       TWINE_PASSWORD: ${{ secrets.pypi_password }}
+  #     run: twine upload --non-interactive --skip-existing --verbose 'dist/*'
 
-    - name: Publish distribution to Test PyPI
-      if: steps.check_secrets.outputs.HAS_SECRET
-      env:
-        TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
-        TWINE_USERNAME: __token__
-        TWINE_NON_INTERACTIVE: 1
-        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
-      run: twine upload --non-interactive --skip-existing --verbose 'dist/*'
+  #   - name: Publish distribution to Test PyPI
+  #     if: steps.check_secrets.outputs.HAS_SECRET
+  #     env:
+  #       TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
+  #       TWINE_USERNAME: __token__
+  #       TWINE_NON_INTERACTIVE: 1
+  #       TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
+  #     run: twine upload --non-interactive --skip-existing --verbose 'dist/*'
